name: pokedex
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # External packages
  get_it: ^7.2.0
  equatable: ^2.0.3

  # Internal packages
  data:
    path: ./packages/data
  domain:
    path: ./packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true